name: build
on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install GCC/G++
        uses: egor-tensin/setup-gcc@v1
      - name: build
        run: |
          sudo apt-get install libcurl4-gnutls-dev
          cd linux
          cd "Discord Music Bot Installer and Runner"
          g++ -std=c++20 'Discord Music Bot Installer and Runner.cpp' -lcurl -o discord-music-bot-installer
          mkdir artifacts
          mv discord-music-bot-installer artifacts/discord-music-bot-installer
          mv "Discord Music Bot Installer and Runner.cpp" artifacts/src.cpp
      - name: upload-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-artifacts
          path: "linux/Discord Music Bot Installer and Runner/artifacts"
